# Dependencies
markdown:             kramdown
highlighter:          rouge

url: "https://jordangeorge.github.io/"
# github:
#   repo:               https://github.com/jordangeorge/jordangeorge.github.io

# Permalinks
# permalink:            pretty

# Setup
title:                Jordan George
description:          'Undergraduate software developer'
baseurl:              ''
favicon:              /public/images/favicon.ico

author:
  name:               'Jordan George'
  url:                jordangeorge.github.io

paginate:             5
paginate_path: "blog/page:num"
permalink: /blog/:title

plugins:
  - jekyll
  - jekyll-paginate
  # - jekyll-feed

collections:
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
