# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:            pretty
relative_permalinks:  false

# Setup
title:            Jordan George
description:      'Undergraduate software developer'
baseurl:          ''

# Assets
pdfs:             '/pdf'

author:
  name:           'Jordan George'
  url:            jordangeorge.github.io

github:
  repo:           https://github.com/jordangeorge/jordangeorge.github.io

# Pagination
paginate:         5

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed

collections:
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
