# Dependencies
markdown:             kramdown
highlighter:          rouge

url:                  "https://jordangeorge.github.io/"

permalink:            /blog/:title

title:                Jordan George
description:          'Undergraduate software developer'
baseurl:              ''
favicon:              /public/images/favicon.ico

author:
  name:               'Jordan George'
  url:                jordangeorge.github.io

paginate:             3
paginate_path:        blog/page:num

plugins:
  - jekyll-paginate

collections:
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
